application: engaged-context-254
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: Main.app
  
- url: /_ah/spi/.*
  script: Main.app
  
  
libraries:
- name: webapp2
  version: "2.5.1"
