application: engaged-context-254
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /_ah/spi/.*
  script: api_server.application
  secure: always

- url: /processupload
  script: process_image_blobstore.application
 
- url: /uploadimage
  script: process_image_blobstore.application

- url: /privacypolicy
  script: privacy_policy.application
  
- url: /termsofservice
  script: terms_of_service.application

libraries:
- name: webapp2
  version: "2.5.1"
