application: engaged-context-254
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: api_server.application
  secure: always
  
- url: /_ah/spi/.*
  script: api_server.application
  secure: always
  
- url: /process_upload
  script: process_image_blobstore.py
  secure: always
  
libraries:
- name: webapp2
  version: "2.5.1"
